GET http://localhost:3000/user

###
GET http://localhost:3000/user/2

###
POST http://localhost:3000/user
content-type: application/json

{
    "name": "Zelão",
    "email": "zelao3@teste.com.br",
    "password":  "123teste"
}

###
PATCH http://localhost:3000/user/3
content-type: application/json

{
    "name": "Zelão 3"
}


###
DELETE http://localhost:3000/user/2